use db_estoque;

CREATE TABLE tb_produtos(
	ID bigint auto_increment,
    NOME VARCHAR (60) NOT NULL,
    MODELO VARCHAR(60) NOT NULL, 
    PRECO INT(255) NOT NULL,
    MARCA_ID bigint NOT NULL,
    
    PRIMARY KEY(ID),
    foreign key (MARCA_ID) REFERENCES tb_marcas(id)

);


SELECT * FROM tb_marcas;
SELECT *FROM tb_produtos;

/*DADOS DO PRODUTO NIKE*/
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "SB", 80.00, 1);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "DRI FIT", 90.00, 1);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "SPORTWEAR", 80.00, 1);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "SWOOSH", 100.00, 1);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CALÇA", "MOLETOM", 80.00, 1);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CALÇA", "MOLETOM ", 90.00, 1);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CALÇA", "JEANS", 250.00, 1);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("TENIS", "AIFORCE", 300.00, 1);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("TENIS", "JORDAN 4", 500.00, 1);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("TENIS", "JORDAN 4", 80.00, 1);

/*PRODUTOS FATAL SURF*/
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "POLO", 80.00, 3);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "MANGA LONGA", 90.00, 3);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "T-SHIRT", 100.00, 3);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("BERMUDA", "SURFISTA", 100.00, 3);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("JAQUETA", "CORTA VENT", 100.00, 3);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("JAQUETA", "CORTA VENTO", 150.00, 3);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CALÇA", "JEANS", 250.00, 3);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("MEIA", "CANO LONGO", 30.00, 3);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("BLUSA", "CANGURU", 250.00, 3);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("BLUSA", "CANGURU", 200.00, 3);

/*PRODUTOS ADIDAS*/
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("TENIS", "LITE RACER", 160.00, 11);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("TENIS", "RUN FALCON", 250.00, 11);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("TENIS", "ON THE GAME", 280.00, 11);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "CLEAR VISION ", 80.00, 11);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "CLEAR VISION", 850, 11);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "LOGO LINEAR", 80.00, 11);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "LOGO LINEAR", 100.00, 11);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "ESSENTIALS", 80.00, 11);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "ESSENTIALS", 90, 11);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CAMISETA", "ESSENTIALS", 100.00, 11);

/*PRODUTOS ZARA*/
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CASACO", "DUPLA FACE", 700.00, 12);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CASACO", "DUPLA FACE", 600.00, 12);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CASACO", "DUPLA FACE", 700.00, 12);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CASACO ", "CONFORTO", 860.00, 12);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CASACO", "TRICO COM CAPUZ", 500.00, 12);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("CASACO", "EFEITO ENCERADO", 500.00, 12);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("JAQUETA", "DENIM BÁSICA", 460.00, 12);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("JAQUETA", "DENIM BÁSICA", 470.00, 12);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("JAQUETA", "DENIM BÁSICA", 500.00, 12);
INSERT INTO tb_produtos (NOME, MODELO, PRECO, MARCA_ID) VALUE ("JAQUETA", "DENIM BÁSICA", 400.00, 12);


SELECT * FROM tb_produtos
	inner join tb_marcas on tb_marcas.id = tb_produtos.marca_id;
    
SELECT tb_produtos.nome, tb_produtos.preco, tb_marcas.nome from tb_produtos
	inner join tb_marcas on tb_marcas.id = tb_produtos.marca_id
WHERE tb_marcas.nome Like "%Adi%"
and tb_produtos.preco > 50
and tb_produtos.nome Like "%Cami%";

SELECT tb_produtos.nome, tb_produtos.preco, tb_marcas.nome from tb_produtos
	inner join tb_marcas on tb_marcas.id = tb_produtos.marca_id
where tb_produtos.nome Like "%Te%"
or tb_produtos.nome Like "%Cami%";

SELECT * from tb_produtos
	left join tb_marcas on tb_marcas.id = tb_produtos.marca_id;
